

Saliva*, Noncoagulated Whole Blood*, Noncoagulated Umbilical Cord Blood*, Buffy Coat*, Buccal Cells, Tissue*, 
Dried Blood Spot*, Cell Suspension*,  Cell Pellet*

INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0001', 'Saliva');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0002', 'Noncoagulated Whole Blood');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0003', 'Noncoagulated Umbilical Cord Blood');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0004', 'Buffy Coat');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0005', 'Buccal Cells');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0006', 'Tissue');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0007', 'Dried Blood Spot');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0008', 'Cell Suspension');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0009', 'Cell Pellet');

CREATE TABLE TEST_USER.ALLOWED_SAMPLE_TYPE
	(
	ALLOWED_TYPE_ID  CHAR(6),
	DESCRIPTION   VARCHAR2(150),
	CONSTRAINT  allowed_sample_type_pk PRIMARY KEY (ALLOWED_TYPE_ID)
	);


	
	

Water, Tris buffer (without EDTA), Tris-EDTA buffer, Other (describe)

INSERT INTO TEST_USER.BUFFER_TYPE (BUFFER_TYPE_ID, DESCRIPTION) VALUES ('BT001', 'Water');
INSERT INTO TEST_USER.BUFFER_TYPE (BUFFER_TYPE_ID, DESCRIPTION) VALUES ('BT002', 'Tris buffer (without EDTA)');
INSERT INTO TEST_USER.BUFFER_TYPE (BUFFER_TYPE_ID, DESCRIPTION) VALUES ('BT003', 'Tris-EDTA buffer');
INSERT INTO TEST_USER.BUFFER_TYPE (BUFFER_TYPE_ID, DESCRIPTION) VALUES ('BT004', 'Other');


CREATE TABLE BUFFER_TYPE
(
BUFFER_TYPE_ID  CHAR(6),
DESCRIPTION   VARCHAR2(30),
CONSTRAINT  buffer_type_pk PRIMARY KEY (BUFFER_TYPE_ID)
);

EDTA, Citrate, Heparin, PaxGene DNA, PaxGene RNA, other (describe)
CREATE TABLE TUBE_TYPE
(
TUBE_TYPE_ID  CHAR(5),
DESCRIPTION   VARCHAR2(30),
CONSTRAINT  tube_type_pk PRIMARY KEY (TUBE_TYPE_ID)
);

INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'EDTA');
INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'Citrate');
INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'Heparin');
INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'PaxGene DNA');
INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'PaxGene RNA');
INSERT INTO TUBE_TYPE (TUBE_TYPE_ID, DESCRIPTION) VALUES ('TT001', 'Other');




CREATE TABLE PRESERVATION_METHOD
(
PRESERVATION_METHOD_ID  CHAR(5),
DESCRIPTION   VARCHAR2(30),
CONSTRAINT  preservation_method_pk PRIMARY KEY (PRESERVATION_METHOD_ID)
);


Flash frozen, RNA Later, All Protect, OCT embedded, Formalin fixation, Ethanol fixation, FFPE, freeze dried

INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM001', 'Flash Frozen');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM002', 'RNA Later');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM003', 'All Protect');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM004', 'OCT Embedded');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM005', 'Formalin Fixation');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM006', 'Ethanol Fixation');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM007', 'FFPE');
INSERT INTO TEST_USER.PRESERVATION_METHOD (COLLECTION_METHOD_ID, DESCRIPTION) VALUES ('CM008', 'Freeze Dried');


CREATE TABLE COLLECTION_METHOD
(
COLLECTION_METHOD_ID  CHAR(5),
DESCRIPTION   VARCHAR2(30),
CONSTRAINT  collection_method_pk PRIMARY KEY (COLLECTION_METHOD_ID)
);


CREATE TABLE MCHEAR_SAMPLE
	(
	SAMPLE_ID	CHAR(9),
	SAMPLE_NAME	VARCHAR2(120),
	EXP_ID	CHAR(7),
	USER_DESCRIPTION	VARCHAR2(4000),
	GENUSORSPECIES_ID	NUMBER(6),
	LOCID	CHAR(6),
	USER_DEFINED_SAMPLE_TYPE VARCHAR2(100),
	USER_DEFINED_GOS VARCHAR2(30),
	VOLUME	NUMBER(11),
	VOL_UNITS	VARCHAR2(26),
	CURRENT_VOLUME	NUMBER(11),
	CURR_VOL_UNITS	VARCHAR2(26),
	CONCENTRATION NUMBER(11),
	CONCENTRATION_UNITS VARCHAR2(26),
	WEIGHT NUMBER(11),
	WEIGHT_UNITS VARCHAR2(26),
	IS_FROZEN BOOLEAN,
	PREV_FROZEN BOOLEAN,
	N_FREEZE_THAWS NUMBER(3),
	STATUS	CHAR(1),
	DATE_CREATED DATE(7),
	SAMPLE_TYPE_ID	CHAR(7),
	SUBJECT_ID	CHAR(9), 
	LOCATION_ID CHAR(6)
	
	CELL_COUNT 
	SEQUENCER 
	READ_LENGTH
	ABCHOICE
	INDEX_NUMBER  INTEGER,
	BUFFER_TYPE_ID  CHAR(6),
	TUBE_TYPE_ID CHAR(5),
	PRESERVATION_METHOD_ID CHAR(5),
	COLLECTION_METHOD_ID CHAR(5),
	NANODROP_CONCENTRATION NUMBER(11),
	TWO_SIXTY_TWO_EIGHTY_CONC NUMBER(11),
	TWO_SIXTY_TWO_THIRTY_CONC NUMBER(11),
	FLUOROMETRIC_CONCENTRATION NUMBER(11),
	RNA_INTEGRITY 
	)

	


ID Conventions;

BufferType  : "BT"
TubeType : "TT"
PreservationMethod : "PM"
CollectionMethod : "CM"
Allowed Type : "AT"