CREATE TABLE MCHEAR.SERVICE_REQUESTS
	(
	SERVICE_REQUEST_ID CHAR(7),
	REQUEST_DATE TIMESTAMP, 
	PROJECT_NAME VARCHAR2(120),
	PI_FIRSTNAME VARCHAR2(20),
	PI_LASTNAME VARCHAR2(30), 
	PI_PHONE VARCHAR2(26), 
	PI_EMAIL VARCHAR2(50),
	PI_ADDRESS VARCHAR2(100), 
	ORGANIZATION VARCHAR2(120), 
	LAB VARCHAR2(100), 
	DEPARTMENT VARCHAR2(50), 
	CONTACT_FIRSTNAME VARCHAR2(20), 
	CONTACT_LASTNAME VARCHAR2(30), 
	CONTACT_PHONE VARCHAR2(26), 
	CONTACT_EMAIL VARCHAR2(50), 
	CONTACT_ADDRESS VARCHAR2(100),
	STATUS CHAR(3),
	
 	CONSTRAINT  mc_service_request_pk PRIMARY KEY (SERVICE_REQUEST_ID)
	)
	
	