CREATE TABLE TEST_USER.LABS
	(
	LAB_ID CHAR(4),
	LAB_NAME VARCHAR2(50),
	CONSTRAINT LABS_PK PRIMARY KEY (LAB_ID)
	)	 
	
INSERT INTO TEST_USER.LABS (LAB_ID, LAB_NAME) VALUES ('L001', 'Metabolomics');
INSERT INTO TEST_USER.LABS (LAB_ID, LAB_NAME) VALUES ('L002', 'BRIR');
