
CREATE_TABLE TEST_USER.MCHEAR_SAMPLE
	(
	MCHEAR_SAMPLE_ID CHAR(9),
	SUBJECT_ID, CHAR(9),
	EXP_ID, CHAR(7),
	RESEARCHER_SAMPLE_ID, VARCHAR2(120),
	RESEARCHER_SUBJECT_ID VARCHAR2(120),
	USER_DEFINED_SAMPLE_TYPE VARCHAR2(100),
	SAMPLE_TYPE_ID CHAR(7),
	DATE_CREATED TIMESTAMP,
	LOCID	CHAR(6),
	STATUS	CHAR(1),
	
	CONSTRAINT mchear_sample_sampleid_pk PRIMARY KEY (SAMPLE_ID)
	);

CREATE_TABLE TEST_USER.SAMPLE_ANALYSIS_OPTIONS
	(
	SAMPLE_ID CHAR(9),
	SEQUENCER
	READ_LENGTH INTEGER,
	AB_CHOICE 
	)
	
CREATE TABLE TEST_USER.SAMPLE_STATE
	(
	SAMPLE_STATE_ID CHAR(9),
	SAMPLE_ID CHAR(7),
	DATE_UPDATED TIMESTAMP, 
	VOLUME NUMBER(11), 
	VOL_UNITS CHAR(2), 
	CONCENTRATION NUMBER, 
	CONC_UNITS VARCHAR2(30),
	WEIGHT NUMBER,
	WEIGHT_UNITS CHAR(2),
	IS_FROZEN BOOLEAN,
	EVER_FROZEN BOOLEAN,
	N_FREEZE_THAW_CYCLES INTEGER,
	CELL_COUNT LONGINTEGER,
	NANODROP_CONCENTRATION NUMBER,
	NANODROP_CONC_UNITS VARCHAR2(30),
	TWO60280_CONCENTRATION NUMBER,
	TWO60280_CONC_UNITS VARCHAR2(30),
	TWO60230_CONCENTRATION NUMBER,
	TWO60230_CONC_UNITS VARCHAR2(30),
	FLUOROMETRIC_CONCENTRATION NUMBER,
	FLUOROMETRIC_CONC_UNITS VARCHAR2(30), 
	RNA_INTEGRITY LONGINTEGER,
	DATE_UPDATED TIMESTAMP,  
	CONSTRAINT mchear_sstate_pk PRIMARY KEY (SAMPLE_STATE_ID)
	)
	
CREATE TABLE TEST_USER.CONCENTRATION_UNITS
	(
	SHORT_CODE CHAR(5),
	DESCRIPTION VARCHAR2(40),
	UPPER_UNIT CHAR(2),
	LOWER_UNIT CHAR(2),
	CONSTRAINT mchear_conc_units_pk PRIMARY KEY (SHORT_CODE)
	)
