CREATE TABLE TEST_USER.ASSAY_ALLOWED_SAMPLE_TYPE
(
ASSAY_ID CHAR(7) NOT NULL, 
ALLOWED_TYPE_ID CHAR(6) NOT NULL,
FOREIGN KEY (ASSAY_ID)  REFERENCES TEST_USER.ASSAYS (ASSAY_ID),
FOREIGN KEY (ALLOWED_TYPE_ID)  REFERENCES TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID)   
)


INSERT INTO TEST_USER.ASSAY_ALLOWED_SAMPLE_TYPE (ASSAY_ID, ALLOWED_TYPE_ID) VALUES ('MA00001',  )

INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0011', 'Serum/Plasma');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0012', 'Serum');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0013', 'Plasma');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0014', 'Urine');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0015', 'Tissue');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0016', 'Immunoprecipitated (IP) DNA');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0017', 'Cross-linked DNA');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0018', 'RNA');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0019', 'cDNA');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0020', 'Cells');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0021', 'Feces');
INSERT INTO TEST_USER.ALLOWED_SAMPLE_TYPE (ALLOWED_TYPE_ID, DESCRIPTION) VALUES ('AT0022', 'Reproductive Tissue');